disabled_rules:
- identifier_name
- private_over_fileprivate

opt_in_rules:
- closure_spacing
- contains_over_first_not_nil
- empty_collection_literal
- empty_count
- empty_string
- fatal_error_message
- first_where
- force_unwrapping
- last_where
- literal_expression_end_indentation
- operator_usage_whitespace
- overridden_super_call
- redundant_nil_coalescing 
- sorted_first_last
- toggle_bool
- unneeded_parentheses_in_closure_argument
- unused_import
- yoda_condition

excluded:
- Carthage
- Pods

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25
    
force_cast: warning
force_try: warning

reporter: "xcode"

